name: Deploy College API to AWS EC2

on:
  push:
    branches: [ main ]  # Adjust this to your main branch name if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci

    - name: Create .env file
      run: |
        echo "PORT=${{ secrets.PORT }}" >> .env
        echo "FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }}" >> .env
        echo "FIREBASE_PRIVATE_KEY=${{ secrets.FIREBASE_PRIVATE_KEY }}" >> .env
        echo "FIREBASE_CLIENT_EMAIL=${{ secrets.FIREBASE_CLIENT_EMAIL }}" >> .env
        echo "REDIS_HOST=${{ secrets.REDIS_HOST }}" >> .env
        echo "REDIS_PORT=${{ secrets.REDIS_PORT }}" >> .env
        echo "REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}" >> .env
        echo "REDIS_URL=${{ secrets.REDIS_URL }}" >> .env

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Setup SSH config
      run: |
        mkdir -p ~/.ssh
        echo "Host ec2-instance" >> ~/.ssh/config
        echo "  HostName ${{ secrets.EC2_HOST }}" >> ~/.ssh/config
        echo "  User ${{ secrets.EC2_USER }}" >> ~/.ssh/config
        echo "  StrictHostKeyChecking no" >> ~/.ssh/config

    - name: Create deployment package
      run: |
        # Create a temporary directory for deployment
        mkdir -p /tmp/deploy
        
        # Copy necessary files to the deployment directory
        cp -R * /tmp/deploy/ || true
        cp .env /tmp/deploy/ || true
        
        # Remove unnecessary files
        rm -rf /tmp/deploy/.git /tmp/deploy/.github /tmp/deploy/node_modules
        
        # Create archive from deployment directory
        tar -czf deploy.tar.gz -C /tmp/deploy .

    - name: Deploy to EC2
      run: |
        # Copy files to EC2
        scp deploy.tar.gz ec2-instance:~/counselling/Backend/deploy.tar.gz
        
        # Execute remote deployment script
        ssh ec2-instance "
          cd ~/counselling/Backend
          
          # Debug - show current directory and files
          pwd
          ls -la
          
          # Create directory if it doesn't exist
          mkdir -p College_api
          
          # Extract files - use absolute path to be sure
          tar -xzf ~/counselling/Backend/deploy.tar.gz -C College_api
          
          # Install dependencies
          cd College_api
          npm ci --production
          
          # Restart service using PM2
          if pm2 list | grep -q \"college-api\"; then
            pm2 restart college-api
          else
            pm2 start src/index.js --name \"college-api\"
          fi
          
          # Remove the tar file after successful deployment
          rm ~/counselling/Backend/deploy.tar.gz
        "
